/**
 * NOTE: Code Launch 처리 단계별 에러 코드 Enum
 */
export enum ErrorCode {
    // NOTE: Job 처리 단계
    JOB_UNKNOWN = 'JOB_UNKNOWN',
    JOB_PROCESSING_FAILED = 'JOB_PROCESSING_FAILED',

    // NOTE: Docker 이미지/컨테이너 단계
    IMAGE_PULL_FAILED = 'IMAGE_PULL_FAILED',
    CONTAINER_CREATE_FAILED = 'CONTAINER_CREATE_FAILED',
    CONTAINER_START_FAILED = 'CONTAINER_START_FAILED',
    CONTAINER_STOP_FAILED = 'CONTAINER_STOP_FAILED',
    CONTAINER_NOT_RUNNING = 'CONTAINER_NOT_RUNNING',
    CONTAINER_PTY_TIMEOUT = 'CONTAINER_PTY_TIMEOUT',

    // NOTE: PTY 세션 단계
    PTY_SESSION_OPEN_FAILED = 'PTY_SESSION_OPEN_FAILED',
    PTY_STREAM_ERROR = 'PTY_STREAM_ERROR',

    // NOTE: 컴파일/실행 단계
    COMPILE_FAILED = 'COMPILE_FAILED',
    EXECUTION_FAILED = 'EXECUTION_FAILED',
}
